---

- name: Install SVN requirements
  apt:
    name: "{{ svn_packages }}"
    state: present

- name: Install svn optional packages
  apt:
    name: "{{ svn_aditional_packages|default(omit) }}"
    state: present
  when: svn_aditional_packages is defined

- name: Enable apache2 modules
  apache2_module:
    name: "{{ apache2_optional_modules|default(omit) }}"
    state: present
  when: apache2_optional_modules is defined
  notify: Restart apache2
